Added DOCKER_TAGS checks to hooks

diff --git a/tools/hooks/build b/tools/hooks/build
--- a/tools/hooks/build
+++ b/tools/hooks/build
@@ -67,6 +67,11 @@ docker build $xtra \
 
 echo '--------------- tagging '$DOCKER_TAGS
 
+test -n "$DOCKER_TAGS" || {
+  echo "Error, no Docker-Tags." >&2
+  exit 1
+}
+
 echo $DOCKER_TAGS | tr -s ', ' ' ' | while read tag
 do
   test -n "$tag" || continue
diff --git a/tools/hooks/push b/tools/hooks/push
--- a/tools/hooks/push
+++ b/tools/hooks/push
@@ -34,6 +34,11 @@ test -e ../env.sh && {
 
 echo '---------- push '$(pwd)
 
+test -n "$DOCKER_TAGS" || {
+  echo "Error, no Docker-Tags." >&2
+  exit 1
+}
+
 echo $DOCKER_TAGS | tr -s ', ' ' ' | while read -r tag
 do
   test -n "$tag" || continue
